#!/usr/bin/env bash
PARENT_PATH=$(cd "$(dirname "{BASH_SOURCE[0]}")"; pwd -P)
cd $PARENT_PATH

source airbook/bin/activate

export FLASK_APP='backend/app.py'
export FLASK_ENV='development'
sudo service mysql start
flask run
