#!/usr/bin/env bash
PARENT_PATH=$(cd "$(dirname "{BASH_SOURCE[0]}")"; pwd -P)
cd $PARENT_PATH

if [[ "$VIRTUAL_ENV" == "" ]]; then
    source airbook/bin/activate
fi

scripts/dbreset
python -m unittest discover -v